import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({ name }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Richard's Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>{name}</h1>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;

export async function getStaticProps(context) {
	const response = await fetch("http://localhost:3000/api/hello");
	const data = await response.json();

	return {
		props: data,
	};
}
